[package]
name = "tauri-cookie-fetch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "^0.11", features = ["cookies"] }
reqwest_cookie_store = "^0.6"
deadpool = "^0.10"
async-trait = "^0.1"
tauri = { version = "1.5", features = ["shell-open", "http-api"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.108"
